name = "NahaXMLUtils"
uuid = "a43006d0-e7b0-4945-abab-c94506b32220"
authors = ["MarkNahabedian <naha@mit.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
XML = "72c71f33-b9b6-44de-8c94-c961784809e2"

[compat]
XML = "0.3.6"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
